name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Helps setup-java cache downloads get unstuck
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: maven
      - name: Build
        run: docker build -t galia-plugin-azurestorage:latest -f docker/Linux_x86-64_JDK22/Dockerfile .
      - name: Run
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: docker run -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} -e GITHUB_PAT=${ACTIONS_PAT} -e AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET} -e AZURE_TENANT_ID=${AZURE_TENANT_ID} galia-plugin-azurestorage:latest

